database:
  AMASS_path: "./AMASS" # path to the database
  AMASS_cache_path: "./AMASS_cache"
  fps: 120
  left_foot_index: 7
  right_foot_index: 8
  loss_weight:
    cur_root_xz_velocity: 2.0
    cur_root_y_angular_velocity: 1.0
    cur_foot_relative_position: 2.0
    future_root_xz_position: 3.0

motion_matching:
  init_seq_name: "0005_Walking001_stageii.npz"  # the initial motion for motion matching
  init_seq_idx: 10                              # index of the initial motion in the database
  consider_trajectory_interval: 60              # interval for considering future trajectories
  consider_trajectory_range: 360                # range for considering future trajectories
  search_interval: 110                          # search interval for motion matching
  keypoint_list:                                # the target keypoints for motion matching
    - [0,0]
    - [4, 4]
    - [8, 0]
    - [0, 8]
    - [0, 4]
    - [10, 10]
    - [0, 0]
  touch_threshold: 1                            # threshold for touching the target keypoint
  half_life: 0.2                                # half-life for the spring
  max_iter: 200                                 # maximum iterations for motion matching

visualization:
  down_sample_rate: 5                           # down sample rate for visualization, visualizing every 5 frames
